create table employees
(
    id       bigint generated by default as identity
        primary key,
    emp_name varchar(255),
    name     varchar(255)
);

create table addresses
(
    id          bigint generated by default as identity
        primary key,
    city        varchar(255),
    employee_id bigint
        constraint addresses_employees_id_fkey
            references employees
);

INSERT INTO employees (name) VALUES
                                 ('John Smith'),     -- id=1
                                 ('Jane Doe'),     -- id=2
                                 ('Robert Brown'),    -- id=3
                                 ('Anna Kovács'),     -- id=4
                                 ('Peter Novak'),     -- id=5
                                 ('László Nagy'),     -- id=6
                                 ('Maria Kiss'),      -- id=7
                                 ('Gábor Tóth'),      -- id=8
                                 ('Erika Szabó'),     -- id=9
                                 ('Balázs Varga');    -- id=10

-- John Smith: 1 cím
INSERT INTO addresses (city, employee_id) VALUES
    ('Budapest', 1);

-- Jane Doe: 1 cím
INSERT INTO addresses (city, employee_id) VALUES
    ('Debrecen', 2);

-- Robert Brown: 1 cím
INSERT INTO addresses (city, employee_id) VALUES
    ('Győr', 3);

-- Anna Kovács: 4 cím
INSERT INTO addresses (city, employee_id) VALUES
                                              ('Szeged', 4),
                                              ('Baja', 4),
                                              ('Szolnok', 4),
                                              ('Kaposvár', 4);

-- Peter Novak: 4 cím
INSERT INTO addresses (city, employee_id) VALUES
                                              ('Miskolc', 5),
                                              ('Sopron', 5),
                                              ('Pápa', 5),
                                              ('Szombathely', 5);

-- László Nagy: 2 cím
INSERT INTO addresses (city, employee_id) VALUES
                                              ('Pécs', 6),
                                              ('Dunaújváros', 6);

-- Maria Kiss: 2 cím
INSERT INTO addresses (city, employee_id) VALUES
                                              ('Székesfehérvár', 7),
                                              ('Veszprém', 7);

-- Gábor Tóth: 3 cím
INSERT INTO addresses (city, employee_id) VALUES
                                              ('Kecskemét', 8),
                                              ('Salgótarján', 8),
                                              ('Békéscsaba', 8);

-- Erika Szabó: 3 cím
INSERT INTO addresses (city, employee_id) VALUES
                                              ('Nyíregyháza', 9),
                                              ('Tatabánya', 9),
                                              ('Siófok', 9);

-- Balázs Varga (id=10) NINCS cím!