server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/employees
    username: employees
    password: employees
  jpa:
    open-in-view: false
    generate-ddl: true
  jackson:
    default-property-inclusion: non_null
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: always
    properties:
      org.quartz.jobStore.driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
      org.quartz.jobStore.class: org.springframework.scheduling.quartz.LocalDataSourceJobStore

management:
  endpoints:
    web:
      exposure:
        include: '*'


logging:
  level:
    employees: DEBUG
    org.hibernate.SQL: TRACE
