server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/employees
    username: employees
    password: employees
  jpa:
    open-in-view: false
    generate-ddl: true
  jackson:
    default-property-inclusion: non_null
  security:
    oauth2:
          resourceserver:
            jwt:
              issuer-uri: https://localhost:9443/realms/EmployeesRealm

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    employees: DEBUG
    org.hibernate.SQL: TRACE