server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/employees
    username: employees
    password: employees
  jpa:
    open-in-view: false
    generate-ddl: true
  jackson:
    default-property-inclusion: non_null

management:
  endpoints:
    web:
      exposure:
        include: '*'


logging:
  level:
    employees: DEBUG
    org.hibernate.SQL: TRACE

employees:
  cors:
    # default will be empty,because of security reasons
    allowed-origins: http://localhost:63342
    # default will be empty,because of security reasons
    mapping: /**
