services:
  training-db:
    image: postgres
    container_name: employees-postgres
    environment:
      - POSTGRES_DB=employees
      - POSTGRES_USER=employees
      - POSTGRES_PASSWORD=employees
    ports:
      - "5432:5432"
    volumes:
      - ../docker/postgress/data:/var/lib/postgresql/data

  training-keycloak:
    image: quay.io/keycloak/keycloak
    container_name: keycloak
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      - KC_HTTPS_CERTIFICATE_FILE=/opt/keycloak/data/cert/server.crt
      - KC_HTTPS_CERTIFICATE_KEY_FILE=/opt/keycloak/data/cert/server.key
    ports:
      # generate the self-signed certificate and key with the createSslCertificate.sh script
      - "9443:8443"
    command: start-dev --https-certificate-file=/opt/keycloak/data/cert/server.crt --https-certificate-key-file=/opt/keycloak/data/cert/server.key
    volumes:
      - ../docker/keycloak/data:/opt/keycloak/data
