### List all employees
GET http://localhost:8081/api/employees
Accept: application/json

### Find employee by id
GET http://localhost:8081/api/employees/6
Accept: application/json

### Find employee by id with etag
GET http://localhost:8081/api/employees/3
If-None-Match: "0"
Accept: application/json

### Find employee by id with date
GET http://localhost:8081/api/employees/6
If-Modified-Since: Tue, 22 Jul 2025 08:45:20 GMT
Accept: application/json

### Create employee
POST http://localhost:8081/api/employees
Content-Type: application/json
Accept: application/json

{
  "name": "Jack Doe"
}

### Validation error
POST http://localhost:8081/api/employees
Content-Type: application/json
Accept: application/json

{
  "name": ""
}

### Update employee
PUT http://localhost:8081/api/employees/6
Content-Type: application/json
Accept: application/json
If-Match: 1

{
  "name": "John Doe"
}

### Delete employee
DELETE http://localhost:8081/api/employees/1
